#!/usr/bin/env sh

set -e

if ! [ -f /usr/share/wordlists/rockyou.txt ]; then
  # Show content without new shell + cd
  SHELL=/bin/true kali-treecd "/usr/share/wordlists" "wordlists" 1 false
  echo
  read -p "Do you want to extract the wordlist rockyou.txt? [Y/n] " confirm
  case $confirm in Y|y|"")
    sudo gunzip -k /usr/share/wordlists/rockyou.txt.gz
    ;;
  esac
  echo
fi
kali-treecd "/usr/share/wordlists" "wordlists" 1 false
